# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration

PreCommit:
  # CoffeeLint:
  #   enabled: true

  # ScssLint:
  #   enabled: true

  # JsLint:
  #   enabled: true
  #   exclude: bundle.js

  # TrailingWhitespace:
  #   enabled: true
  #   exclude:
